# Generated by Django 2.0.4 on 2018-04-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cuenta', models.CharField(max_length=50, null=True)),
                ('texto', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
