# Generated by Django 2.0.2 on 2018-03-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('edad', models.IntegerField(default=0)),
                ('telefono', models.IntegerField(default=0)),
                ('sexo', models.CharField(max_length=10)),
                ('rol', models.CharField(max_length=15)),
                ('fechaInicio', models.DateField()),
                ('activo', models.BooleanField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.IntegerField(default=0)),
                ('tipoPropiedad', models.CharField(max_length=20)),
                ('presupuesto', models.FloatField()),
                ('idC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnection.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Intermediario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.DecimalField(decimal_places=2, max_digits=8)),
                ('experiencia', models.IntegerField(default=0)),
                ('nombreI', models.CharField(max_length=35)),
                ('idI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnection.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('valuacion', models.FloatField()),
                ('tipo', models.CharField(max_length=20)),
                ('informacion', models.CharField(max_length=100)),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bienPoseido', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('idP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnection.Cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
