# Generated by Django 2.0.2 on 2018-03-21 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0002_auto_20180309_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamposAdicionales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('tipo', models.CharField(default='string', max_length=35)),
                ('tabla', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ValoresAdicionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tupla', models.IntegerField(default=0)),
                ('valor', models.CharField(default='', max_length=35)),
                ('id_campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnection.CamposAdicionales')),
            ],
        ),
        migrations.RemoveField(
            model_name='comprador',
            name='idC',
        ),
        migrations.RemoveField(
            model_name='intermediario',
            name='idI',
        ),
        migrations.RemoveField(
            model_name='intermediario',
            name='nombreI',
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='idP',
        ),
        migrations.AddField(
            model_name='comprador',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comprador',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comprador',
            name='fechaInicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='comprador',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='comprador',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='comprador',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='comprador',
            name='rol',
            field=models.CharField(default='comprador', max_length=15),
        ),
        migrations.AddField(
            model_name='comprador',
            name='sexo',
            field=models.CharField(default='femenino', max_length=10),
        ),
        migrations.AddField(
            model_name='comprador',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intermediario',
            name='nombre',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='propietario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propietario',
            name='fechaInicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='propietario',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='rol',
            field=models.CharField(default='comprador', max_length=15),
        ),
        migrations.AddField(
            model_name='propietario',
            name='sexo',
            field=models.CharField(default='femenino', max_length=10),
        ),
        migrations.AddField(
            model_name='propietario',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='presupuesto',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='tipoPropiedad',
            field=models.CharField(default='casa', max_length=20),
        ),
        migrations.AlterField(
            model_name='intermediario',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='intermediario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='informacion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tamano',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(default='casa', max_length=20),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='valuacion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='bienPoseido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbconnection.Propiedad'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='direccion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
