# Generated by Django 2.0.3 on 2018-03-23 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0004_auto_20180322_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propietario',
            name='bienPoseido',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='intermediario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dbconnection.Intermediario'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='propietario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dbconnection.Propietario'),
        ),
    ]
