# Generated by Django 2.0.3 on 2018-03-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0005_auto_20180322_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='rol',
            field=models.CharField(blank=True, choices=[('c', 'comprador'), ('p', 'propietario')], default='c', help_text='rol', max_length=1),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('f', 'femenino'), ('m', 'masculino')], default='f', help_text='sexo', max_length=1),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='rol',
            field=models.CharField(blank=True, choices=[('c', 'comprador'), ('p', 'propietario')], default='c', help_text='rol', max_length=1),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('f', 'femenino'), ('m', 'masculino')], default='f', help_text='sexo', max_length=1),
        ),
    ]
