# Generated by Django 2.0.3 on 2018-03-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0006_auto_20180322_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='intermediario',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intermediario',
            name='fechaInicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='intermediario',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='intermediario',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='intermediario',
            name='rol',
            field=models.CharField(blank=True, choices=[('c', 'comprador'), ('p', 'propietario'), ('i', 'intermediario')], default='c', help_text='rol', max_length=1),
        ),
        migrations.AddField(
            model_name='intermediario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('f', 'femenino'), ('m', 'masculino')], default='f', help_text='sexo', max_length=1),
        ),
        migrations.AddField(
            model_name='intermediario',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='rol',
            field=models.CharField(blank=True, choices=[('c', 'comprador'), ('p', 'propietario'), ('i', 'intermediario')], default='c', help_text='rol', max_length=1),
        ),
        migrations.AlterField(
            model_name='intermediario',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='rol',
            field=models.CharField(blank=True, choices=[('c', 'comprador'), ('p', 'propietario'), ('i', 'intermediario')], default='c', help_text='rol', max_length=1),
        ),
    ]
