# Generated by Django 2.0.3 on 2018-03-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0010_administra_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='cuenta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='intermediario',
            name='cuenta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='cuenta',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='reputacion',
            field=models.CharField(blank=True, choices=[('Buena', 'b'), ('Normal', 'n'), ('Mala', 'm')], max_length=6),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Femenino', 'f'), ('Masculino', 'm')], max_length=8),
        ),
        migrations.AlterField(
            model_name='intermediario',
            name='reputacion',
            field=models.CharField(blank=True, choices=[('Buena', 'b'), ('Normal', 'n'), ('Mala', 'm')], max_length=6),
        ),
        migrations.AlterField(
            model_name='intermediario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Femenino', 'f'), ('Masculino', 'm')], max_length=8),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Apartamento', 'a'), ('Casa', 'c'), ('Terreno', 't'), ('Otro', 'o')], max_length=6),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='reputacion',
            field=models.CharField(blank=True, choices=[('Buena', 'b'), ('Normal', 'n'), ('Mala', 'm')], max_length=6),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Femenino', 'f'), ('Masculino', 'm')], max_length=8),
        ),
    ]
