# Generated by Django 2.0.3 on 2018-03-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbconnection', '0012_auto_20180323_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='reputacion',
            field=models.CharField(blank=True, choices=[('Buena', 'Buena'), ('Normal', 'Normal'), ('Mala', 'Mala')], max_length=10),
        ),
        migrations.AlterField(
            model_name='intermediario',
            name='reputacion',
            field=models.CharField(blank=True, choices=[('Buena', 'Buena'), ('Normal', 'Normal'), ('Mala', 'Mala')], max_length=10),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Apartamento', 'Apartamento'), ('Casa', 'Casa'), ('Terreno', 'Terreno'), ('Otro', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='reputacion',
            field=models.CharField(blank=True, choices=[('Buena', 'Buena'), ('Normal', 'Normal'), ('Mala', 'Mala')], max_length=10),
        ),
    ]
